### ISSUE TITLE
MicroSD breakout board PCB design.

### ISSUE THREAD

**Issue by sakoPO** [microHAL/hardwaretester#11]
SD card should communicate with MCU by SPI.

**Comment by pjacalski** [comment]
Initial commit for PCB design.
https://workspace.circuitmaker.com/Projects/Details/Pawel-Jacalski/UHALMICROSDBREAKOUT

**Comment by sakoPO** [comment]
Please add 2.2uF capacitor on power line, next to 100nF

**Comment by pjacalski** [comment]
Fixed.
